version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    env_file:
      - .env # Add in the .env file manually
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - taskmanagementsystem_sql_data:/var/snap/docker/common/var-lib-docker/volumes/taskmanagementsystem_sql_data/_data
    networks:
      - app-network

volumes:
  taskmanagementsystem_sql_data: 
    
networks:
  app-network:
    driver: bridge

# end of docker file